# .air.toml

# Working directory
root = "."
tmp_dir = "tmp"

[build]
  # Command to build your Gin app
  cmd = "go build -o ./tmp/main ."
  # Binary to run
  bin = "./tmp/main"
  # Include only .go, .mod, and .env files
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Ignore vendor directory
  exclude_dir = ["tmp", "vendor"]
  # Delay after file changes
  delay = 1000 # ms

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[misc]
  clean_on_exit = true
